//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        public int OnlineCourseID { get; set; }
        public string StudentName { get; set; }
        public string CINC { get; set; }
        public string Address { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public string Department { get; set; }
        public string CourseId { get; set; }
        public int Fee { get; set; }
    }
}
