//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrolledStudent
    {
        public int CourseID { get; set; }
        public string StudentName { get; set; }
        public string Email { get; set; }
        public string CNIC { get; set; }
        public string Address { get; set; }
        public int InstructorID { get; set; }
        public int Fee { get; set; }
        public System.DateTime StartDate { get; set; }
        public string Duration { get; set; }
        public string Department { get; set; }
        public int StudentID { get; set; }
        public int EnrolledID { get; set; }
    }
}
