//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institute_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int QuestionID { get; set; }
        public int CourseID { get; set; }
        public int InstructorID { get; set; }
        public int Marks { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Instructor Instructor { get; set; }
    }
}
